In [2]:
"1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。"
import numpy as np
import timeit
a=np.random.randint(0,10,1000000).reshape(100,100,100)

In [3]:
%timeit -n 10 a = 2
for i in a:
    for row in i:
        for j in row:
            j=j+1

35.7 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit -n 10 a = 2
for i in a.flat:
    i=i+1

31.4 ns ± 9.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit -n 10 a = 2
for i in np.nditer(a):
    i=i+1

30 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
"2. 如何從一個陣列中，找出出現頻率最高的數值與位置？"
Z = np.random.randint(0,10,50)
print(Z)

[1 4 9 3 9 9 2 2 2 5 2 9 2 2 4 1 3 0 3 2 3 6 4 9 9 9 4 6 0 3 6 3 1 0 7 8 9
 7 1 2 0 2 6 1 3 1 2 2 6 9]


In [7]:
x=np.argmax(Z)
print(x)
print(Z[x])
b=np.where(Z==Z[x])
print(b)

2
9
(array([ 2,  4,  5, 11, 23, 24, 25, 36, 49], dtype=int32),)


In [8]:
"3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。"
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[6, 1, 7, 1, 0, 8]
[6, 1, 7, 1, 0, 8]
[[0, 7, 8, 6], [5, 9, 6, 7], [6, 1, 1, 3]]
[array([0, 7, 8, 6]), array([5, 9, 6, 7]), array([6, 1, 1, 3])]
[[[1, 6], [3, 4], [3, 7]], [[8, 4], [5, 2], [0, 8]]]
[array([[1, 6],
       [3, 4],
       [3, 7]]), array([[8, 4],
       [5, 2],
       [0, 8]])]


In [9]:
'a'
print(list(a))
'b'
b_list=[]
for i in b:
    b_list.append(list(i))
    print(b_list)
'c'
c_list=[]
for i in range(c.shape[0]):
    for j in range(c.shape[1]):
        c_list.append(list(c[i][j]))
        
        print(c_list)

[6, 1, 7, 1, 0, 8]
[[0, 7, 8, 6]]
[[0, 7, 8, 6], [5, 9, 6, 7]]
[[0, 7, 8, 6], [5, 9, 6, 7], [6, 1, 1, 3]]
[[1, 6]]
[[1, 6], [3, 4]]
[[1, 6], [3, 4], [3, 7]]
[[1, 6], [3, 4], [3, 7], [8, 4]]
[[1, 6], [3, 4], [3, 7], [8, 4], [5, 2]]
[[1, 6], [3, 4], [3, 7], [8, 4], [5, 2], [0, 8]]


In [18]:
array1 = np.array([[10, 8], [3, 5]])
"運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?"
inv_array1=np.linalg.inv(array1)
print(inv_array1)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


In [19]:
a=array1 @ inv_array1
print(a)

[[ 1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00]]


In [20]:
"運用上列array計算特徵值、特徵向量?"
w,v=np.linalg.eig(array1)
print(w,'\n')
print(v)

[13.  2.] 

[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [22]:
"運用上列array計算SVD?"
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))